# WARNING: This Docker Compose file is good enough. But it can definitely be improved for the mini-project.
services:
  web-app:
    build: frontend/
    ports:
      - "8080:80"
  api:
    build: backend/
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=Sup1nf0
      - DB_NAME=mydb
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=Sup1nf0
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: